import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import pLimit from "p-limit";
import { captureStartPageScreenshotToDir } from "./capture-start-screenshot.js";
import { crawlSite } from "./crawl-site.js";
import { dedupeNormalizedUrls, healthSiteOutputDirName, loadUrlsFromTxt, siteIdFromUrl } from "./load-urls.js";
import {
  buildRunSummaryPayload,
  generateRunSummary,
} from "./run-summary-ai.js";
import { attachPageSpeedInsights, resolvePageSpeedApiKey } from "./pagespeed-insights.js";
import { attachViewportChecks } from "./viewport-check.js";
import { runSmartAnalysis } from "./ollama-agent.js";
import type { HealthProgressEvent } from "./progress-events.js";
import { masterReportBaseName, perSiteReportBaseName } from "./report-names.js";
import {
  buildHealthIndexHtml,
  buildMasterRedirectHtml,
  buildRunSummaryHtml,
  writeMasterHealthReports,
  writeSiteHealthReports,
} from "./report-site.js";
import type { SiteHealthReport } from "./types.js";

function runId(): string {
  const d = new Date();
  const stamp = d.toISOString().replace(/[:.]/g, "-");
  return `${stamp}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Human-readable run label so SEO users don't have to parse ISO timestamps
 * out of a dropdown. Examples:
 *   "realdrseattle.com · Apr 21, 7:14 PM · 21 pages"
 *   "realdrseattle.com + 2 more · Apr 21, 7:14 PM · 58 pages"
 */
export function computeRunLabel(
  startedAtIso: string | undefined,
  sites: { hostname: string; pagesVisited?: number }[],
): string {
  const d = startedAtIso ? new Date(startedAtIso) : new Date();
  const when = d.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
  const host = sites[0]?.hostname ?? "unknown";
  const extra = sites.length > 1 ? ` + ${sites.length - 1} more` : "";
  const pageCount = sites.reduce((a, s) => a + (s.pagesVisited ?? 0), 0);
  const pageSuffix = pageCount > 0 ? ` · ${pageCount} page${pageCount === 1 ? "" : "s"}` : "";
  return `${host}${extra} · ${when}${pageSuffix}`;
}

export interface HealthRunMeta {
  runId: string;
  /** Human-readable run label, e.g. "realdrseattle.com · Apr 21, 7:14 PM · 21 pages". */
  label?: string;
  /** When the run started (ISO 8601). Omitted in older run-meta.json files. */
  startedAt?: string;
  /** Wall-clock duration for the full run (ms). Omitted in older files. */
  durationMsTotal?: number;
  generatedAt: string;
  urlsSource: "file" | "inline";
  urlsFile?: string;
  totalSites: number;
  siteFailures: number;
  sites: {
    hostname: string;
    startUrl: string;
    failed: boolean;
    pagesVisited: number;
    brokenLinks: number;
    durationMs: number;
    reportHtmlHref: string;
  }[];
  /** Full combined HTML (MASTER-all-sites-*.html): screenshots, PageSpeed, all tables. */
  masterHtmlHref: string;
  /** Compact stats-only HTML for small run-level PDFs (`run-summary.html`). */
  runSummaryHtmlHref?: string;
  indexHtmlHref: string;
  /** Relative path to Markdown AI summary when generated. */
  aiSummaryHref?: string;
  aiSummary?: {
    generatedAt?: string;
    skippedReason?: string;
  };
  features?: {
    pageSpeedStrategies?: ("mobile" | "desktop")[];
    viewportCheck?: boolean;
  };
  /** Aggregated agentic-mode summary across every site in the run. When
   *  present, the dashboard renders a "🧠 Agentic plan" strip on /run/:id.
   *  Absent when no site ran agentically (Ollama offline or kill-switched). */
  agentic?: {
    ranCount: number;        // sites where agentic brain fired
    totalSites: number;      // total sites in the run
    strategies: string[];    // union of strategies chosen across sites
    prioritySections: string[]; // union of priority sections
    focusKeywords: string[]; // union of focus keywords
    replanCountTotal: number;
    reorderedCountTotal: number;
    plannerMsTotal: number;  // ms spent in LLM planner/prioritizer calls
  };
}

export async function orchestrateHealthCheck(options: {
  /** Read URLs from this file (mutually exclusive with `urls`). */
  urlsFile?: string;
  /** Use these URLs directly (mutually exclusive with `urlsFile`). */
  urls?: string[];
  outRoot: string;
  maxPages: number;
  maxLinkChecks: number;
  concurrency: number;
  /** Parallel HTTP requests per site (crawl + link checks). */
  fetchConcurrency: number;
  requestTimeoutMs: number;
  /** Optional Lighthouse lab data via Google PageSpeed Insights API. */
  pageSpeed?: {
    enabled: boolean;
    strategies: ("mobile" | "desktop")[];
    maxUrls: number;
    concurrency: number;
    timeoutMs: number;
  };
  /** Optional Chromium mobile/desktop viewport smoke loads. */
  viewportCheck?: {
    enabled: boolean;
    maxUrls: number;
    timeoutMs: number;
    concurrency: number;
  };
  /** Optional Markdown executive summary generated by local Ollama. */
  aiSummary?: boolean;
  /** Run Ollama-powered autonomous smart analysis after crawl. */
  smartAnalysis?: boolean;
  /** Run Googlebot-grade post-crawl enrichers (robots.txt compliance,
   *  redirect chains, JSON-LD, hreflang, sitemap diff, canonical chains).
   *  Defaults to true. Adds ~5-15s to each site depending on size and
   *  enables the Site-Audit Council. */
  enrich?: boolean;
  onProgress?: (event: HealthProgressEvent) => void;
}): Promise<{ runId: string; runDir: string; siteFailures: number }> {
  const rid = runId();
  const runDir = path.resolve(options.outRoot, rid);
  await mkdir(runDir, { recursive: true });

  let urls: string[];
  let urlsSource: "file" | "inline";
  let resolvedUrlsFile: string | undefined;
  if (options.urls && options.urls.length > 0) {
    urls = dedupeNormalizedUrls(options.urls);
    urlsSource = "inline";
  } else if (options.urlsFile) {
    urls = await loadUrlsFromTxt(options.urlsFile);
    urlsSource = "file";
    resolvedUrlsFile = path.resolve(options.urlsFile);
  } else {
    throw new Error("orchestrateHealthCheck: pass either urlsFile or a non-empty urls array");
  }
  if (urls.length === 0) {
    throw new Error(urlsSource === "file" ? `No URLs found in ${resolvedUrlsFile}` : "No valid URLs in request");
  }

  const emit = options.onProgress;
  const runStartedAt = new Date().toISOString();
  const runStartWallMs = Date.now();
  const sitesMeta = urls.map((u) => ({
    siteId: siteIdFromUrl(u),
    hostname: new URL(u).hostname,
    startUrl: u,
  }));
  emit?.({
    type: "run_start",
    runId: rid,
    runDir,
    totalSites: urls.length,
    startedAt: runStartedAt,
    sites: sitesMeta,
  });

  async function runOneSite(idx: number, startUrl: string): Promise<SiteHealthReport & { failed: boolean }> {
    const index = idx + 1;
    const siteId = siteIdFromUrl(startUrl);
    const hostname = new URL(startUrl).hostname;
    const outputDirName = healthSiteOutputDirName(idx, startUrl);

    emit?.({
      type: "site_start",
      runId: rid,
      siteId,
      hostname,
      startUrl,
      index,
      totalSites: urls.length,
    });

    const startedAt = new Date().toISOString();
    let crawl: import("./types.js").CrawlSiteResult;
    try {
      const enrichEnabled = options.enrich !== false;
      // Agentic mode is ON by default — crawl-site falls back to pure BFS
      // when Ollama isn't reachable, and respects QA_AGENT_NO_AGENTIC=1 as
      // a universal kill-switch for operators who want deterministic crawls.
      const agenticEnabled = process.env.QA_AGENT_NO_AGENTIC?.trim() !== "1";
      crawl = await crawlSite({
        startUrl,
        maxPages: options.maxPages,
        maxLinkChecks: options.maxLinkChecks,
        requestTimeoutMs: options.requestTimeoutMs,
        fetchConcurrency: options.fetchConcurrency,
        retainBodies: enrichEnabled, // enrichers re-parse bodies; dropped before persist
        agentic: agenticEnabled,
      });

      // ── Post-crawl steps run IN PARALLEL for speed ──────────────
      const siteDirEarly = path.join(runDir, outputDirName);
      const parallelTasks: Promise<void>[] = [];

      // Screenshot (always)
      parallelTasks.push(
        captureStartPageScreenshotToDir({
          startUrl,
          siteOutDir: siteDirEarly,
          requestTimeoutMs: options.requestTimeoutMs,
        }).then((ss) => { crawl.startPageScreenshot = ss; })
         .catch(() => { /* screenshot failure is non-fatal */ }),
      );

      // PageSpeed (optional)
      const ps = options.pageSpeed;
      if (ps?.enabled) {
        const apiKey = resolvePageSpeedApiKey();
        if (apiKey) {
          parallelTasks.push(
            attachPageSpeedInsights(crawl, {
              apiKey,
              strategies: ps.strategies.length > 0 ? ps.strategies : ["desktop"],
              maxUrls: ps.maxUrls,
              concurrency: ps.concurrency,
              timeoutMs: ps.timeoutMs,
            }).then(() => {}),
          );
        }
      }

      // Viewport checks (optional)
      const vc = options.viewportCheck;
      if (vc?.enabled) {
        parallelTasks.push(
          attachViewportChecks(crawl, {
            maxUrls: vc.maxUrls,
            timeoutMs: vc.timeoutMs,
            concurrency: vc.concurrency,
          }).then(() => {}),
        );
      }

      // Wait for ALL post-crawl steps to finish in parallel
      await Promise.allSettled(parallelTasks);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      emit?.({
        type: "site_error",
        runId: rid,
        siteId,
        hostname,
        startUrl,
        index,
        totalSites: urls.length,
        message,
      });
      throw err;
    }

    const finishedAt = new Date().toISOString();

    const report: SiteHealthReport = {
      siteId: crawl.siteId,
      hostname: crawl.hostname,
      startUrl,
      startedAt,
      finishedAt,
      crawl,
    };

    // ── Post-crawl enrichers (Googlebot-grade audits) ────────────────────
    // Each runs independently; a failure in one doesn't block the others.
    // After all finish, we drop the retained HTML bodies from pages so the
    // persisted report stays small.
    if (options.enrich !== false) {
      const enrichStatus: NonNullable<SiteHealthReport["enrichments"]>["status"] = [];
      const enrichments: NonNullable<SiteHealthReport["enrichments"]> = { status: enrichStatus };
      report.enrichments = enrichments;

      const runEnricher = async <K extends keyof typeof enrichments>(
        name: K & string,
        run: () => Promise<NonNullable<typeof enrichments[K]>>,
      ): Promise<void> => {
        const started = Date.now();
        try {
          const result = await run();
          (enrichments as Record<string, unknown>)[name] = result;
          enrichStatus.push({ name, ok: true, durationMs: Date.now() - started });
        } catch (e) {
          enrichStatus.push({
            name,
            ok: false,
            durationMs: Date.now() - started,
            error: e instanceof Error ? e.message.slice(0, 160) : String(e).slice(0, 160),
          });
        }
      };

      const { enrichRobotsTxt } = await import("./crawl-enrichers/robots-txt.js");
      const { enrichRedirectChains } = await import("./crawl-enrichers/redirect-chain.js");
      const { enrichStructuredData } = await import("./crawl-enrichers/structured-data.js");
      const { enrichHreflang } = await import("./crawl-enrichers/hreflang-audit.js");
      const { enrichSitemapDiff } = await import("./crawl-enrichers/sitemap-diff.js");
      const { enrichCanonicalChains } = await import("./crawl-enrichers/canonical-chain.js");

      // Robots runs first so sitemap-diff can reuse its declared sitemaps.
      await runEnricher("robots", () => enrichRobotsTxt(report));
      const declaredSitemaps = enrichments.robots?.declaredSitemaps ?? [];

      await Promise.allSettled([
        runEnricher("redirectChains", () => enrichRedirectChains(report)),
        runEnricher("structuredData", () => enrichStructuredData(report)),
        runEnricher("hreflang", () => enrichHreflang(report)),
        runEnricher("sitemapDiff", () => enrichSitemapDiff(report, declaredSitemaps)),
        runEnricher("canonicalChains", () => enrichCanonicalChains(report)),
      ]);

      // Drop retained bodies now that enrichers have consumed them; keeps
      // persisted JSON size bounded (a 500-page HTML crawl would otherwise
      // serialize ~50MB+ of duplicated HTML).
      for (const p of crawl.pages) {
        if (p.retainedBody) delete p.retainedBody;
      }
    }

    const siteDir = path.join(runDir, outputDirName);
    const siteFileBase = perSiteReportBaseName(report.hostname, report.finishedAt);
    // Fire-and-forget: write reports in background so the next site can start immediately.
    // Errors are logged but don't block the pipeline.
    const writePromise = writeSiteHealthReports({ report, outDir: siteDir, fileBaseName: siteFileBase, runId: rid })
      .then(() => {})
      .catch((e) => { console.error(`[write-report] ${hostname}: ${e}`); });
    deferredWrites.push(writePromise);

    const failed = crawl.brokenLinks.length > 0 || crawl.pages.some((p) => !p.ok);
    const reportHtmlHref = `${outputDirName}/report.html`;

    emit?.({
      type: "site_complete",
      runId: rid,
      siteId: crawl.siteId,
      hostname: crawl.hostname,
      startUrl,
      index,
      totalSites: urls.length,
      failed,
      pagesVisited: crawl.pagesVisited,
      brokenLinks: crawl.brokenLinks.length,
      durationMs: crawl.durationMs,
      reportHtmlHref,
    });

    return { ...report, failed };
  }

  const results: (SiteHealthReport & { failed: boolean })[] = [];
  const deferredWrites: Promise<void>[] = [];

  if (options.concurrency <= 1) {
    for (let idx = 0; idx < urls.length; idx++) {
      results.push(await runOneSite(idx, urls[idx]));
    }
  } else {
    const limit = pLimit(options.concurrency);
    const tasks = urls.map((startUrl, idx) => limit(() => runOneSite(idx, startUrl)));
    results.push(...(await Promise.all(tasks)));
  }
  // Await all deferred report writes before generating combined reports
  if (deferredWrites.length > 0) await Promise.allSettled(deferredWrites);

  /** Same order as the URL list (Promise.all preserves index order; this is a safety net). */
  results.sort((a, b) => urls.indexOf(a.startUrl) - urls.indexOf(b.startUrl));
  const siteFailures = results.filter((r) => r.failed).length;

  const runFinishedAt = new Date().toISOString();
  const runWallDurationMs = Math.max(0, Date.now() - runStartWallMs);
  const cleanReports = results.map((r) => {
    const { failed: _f, ...rep } = r;
    return rep;
  });
  const masterBase = masterReportBaseName(runFinishedAt);
  await writeMasterHealthReports({
    reports: cleanReports,
    runDir,
    fileBaseName: masterBase,
    meta: {
      runId: rid,
      urlsFile: urlsSource === "file" && resolvedUrlsFile ? resolvedUrlsFile : "(inline)",
      generatedAt: runFinishedAt,
    },
  });

  await writeFile(
    path.join(runDir, "master.html"),
    buildMasterRedirectHtml(`${masterBase}.html`),
    "utf8",
  );

  await writeFile(
    path.join(runDir, "run-summary.html"),
    buildRunSummaryHtml(cleanReports, {
      runId: rid,
      urlsFile: urlsSource === "file" && resolvedUrlsFile ? resolvedUrlsFile : "(inline)",
      generatedAt: runFinishedAt,
      startedAt: runStartedAt,
    }),
    "utf8",
  );

  const indexItems = results.map((r, i) => {
    const folder = healthSiteOutputDirName(i, r.startUrl);
    const base = perSiteReportBaseName(r.hostname, r.finishedAt);
    return {
      hostname: r.hostname,
      htmlHref: `./${folder}/${base}.html`,
      jsonHref: `./${folder}/${base}.json`,
      label: `${base}.html`,
    };
  });
  const urlsLabel =
    urlsSource === "file" && resolvedUrlsFile ? resolvedUrlsFile : "URLs from UI / inline";

  await writeFile(
    path.join(runDir, "index.html"),
    buildHealthIndexHtml({
      runId: rid,
      generatedAt: runFinishedAt,
      urlsFile: urlsLabel,
      masterHtmlPath: `./${masterBase}.html`,
      masterJsonPath: `./${masterBase}.json`,
      items: indexItems,
    }),
    "utf8",
  );

  // ── AI summary (local Ollama) + Smart Analysis run IN PARALLEL ──
  let aiSummaryHref: string | undefined;
  let aiSummary: HealthRunMeta["aiSummary"] | undefined;

  const endTasks: Promise<void>[] = [];

  if (options.aiSummary) {
    endTasks.push(
      (async () => {
        try {
          const { checkOllamaAvailable } = await import("./llm.js");
          const ok = await checkOllamaAvailable();
          if (!ok) {
            aiSummary = {
              skippedReason:
                "Local Ollama not available. Start Ollama and pull the llama3.2 model (ollama pull llama3.2).",
            };
            return;
          }
          const reps = results.map((r) => { const { failed: _f, ...rep } = r; return rep; });
          const payload = buildRunSummaryPayload(reps, rid, runFinishedAt);
          const md = await generateRunSummary(payload);
          await writeFile(path.join(runDir, "ai-summary.md"), md, "utf8");
          aiSummaryHref = "./ai-summary.md";
          aiSummary = { generatedAt: new Date().toISOString() };
        } catch (e) {
          aiSummary = { skippedReason: e instanceof Error ? e.message : String(e) };
        }
      })(),
    );
  }

  if (options.smartAnalysis) {
    endTasks.push(
      (async () => {
        try {
          const reportData = results.map((r) => ({ ...r, failed: undefined })) as SiteHealthReport[];
          const smartResult = await runSmartAnalysis(reportData);
          await writeFile(path.join(runDir, "smart-analysis.json"), JSON.stringify(smartResult, null, 2), "utf8");
        } catch {
          // smart analysis is optional — failure is non-fatal
        }
      })(),
    );
  }

  await Promise.allSettled(endTasks);

  const runMetaSites = results.map((r, i) => ({
    hostname: r.hostname,
    startUrl: r.startUrl,
    failed: r.failed,
    pagesVisited: r.crawl.pagesVisited,
    brokenLinks: r.crawl.brokenLinks.length,
    durationMs: r.crawl.durationMs,
    reportHtmlHref: `${healthSiteOutputDirName(i, r.startUrl)}/report.html`,
  }));
  const runMeta: HealthRunMeta = {
    runId: rid,
    label: computeRunLabel(runStartedAt, runMetaSites),
    startedAt: runStartedAt,
    durationMsTotal: runWallDurationMs,
    generatedAt: runFinishedAt,
    urlsSource,
    urlsFile: resolvedUrlsFile,
    totalSites: urls.length,
    siteFailures,
    sites: runMetaSites,
    masterHtmlHref: `./${masterBase}.html`,
    runSummaryHtmlHref: "./run-summary.html",
    indexHtmlHref: "./index.html",
    aiSummaryHref,
    aiSummary,
    features: {
      pageSpeedStrategies: options.pageSpeed?.enabled ? options.pageSpeed.strategies : undefined,
      viewportCheck: options.viewportCheck?.enabled === true,
    },
    agentic: (() => {
      const metas = results.map((r) => r.crawl.agenticMeta).filter((m): m is NonNullable<typeof m> => !!m);
      if (metas.length === 0) return undefined;
      return {
        ranCount: metas.length,
        totalSites: results.length,
        strategies: Array.from(new Set(metas.map((m) => m.strategy))),
        prioritySections: Array.from(new Set(metas.flatMap((m) => m.prioritySections))).slice(0, 12),
        focusKeywords: Array.from(new Set(metas.flatMap((m) => m.focusKeywords))).slice(0, 12),
        replanCountTotal: metas.reduce((s, m) => s + m.replanCount, 0),
        reorderedCountTotal: metas.reduce((s, m) => s + m.reorderedCount, 0),
        plannerMsTotal: metas.reduce((s, m) => s + m.plannerMs, 0),
      };
    })(),
  };
  await writeFile(path.join(runDir, "run-meta.json"), JSON.stringify(runMeta, null, 2), "utf8");

  const summaryTxt = [
    `QA-Agent health run ${rid}`,
    `URLs: ${urlsLabel}`,
    `Sites: ${urls.length} · Failed (issues found): ${siteFailures}`,
    "",
    ...results.map(
      (r) =>
        `${r.hostname}: pages=${r.crawl.pagesVisited} brokenLinks=${r.crawl.brokenLinks.length} ${r.failed ? "FAIL" : "OK"}`,
    ),
  ].join("\n");
  await writeFile(path.join(runDir, "summary.txt"), summaryTxt, "utf8");

  emit?.({
    type: "run_complete",
    runId: rid,
    runDir,
    siteFailures,
    totalSites: urls.length,
    endedAt: runFinishedAt,
    durationMs: runWallDurationMs,
  });

  return { runId: rid, runDir, siteFailures };
}
